---
  version: '3'
  services:
    app:
      image: quell
      container_name: quell-container
      ports:
        - "8080:8080"
        - "3000:3000"
      volumes:
        - .:/usr/src/app
        - node_modules:/usr/src/app/node_modules
      command: npm-start
      depends_on:
        - redis
    redis:
      ports:
        - "6379:6379"
      image: redis:latest
      command: redis-server
      volumes:
      - cache:/data
  volumes:
    node_modules:
    cache:
      driver: local